name: Continuous Deployment - Run Azure Login with OIDC

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: elisaalcala/mydb:latest
        env:
          MYSQL_ROOT_PASSWORD: 3301
          MYSQL_DATABASE: alcalapp_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

    env: # Global environment
      DB_URL: jdbc:mysql://localhost:3306/alcalapp_db?serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 3301
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: mvn test
        
      - name: Generate tag
        id: project
        run: echo "tag=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)" >> $GITHUB_OUTPUT
        
      - name: Generate Docker image
        run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/alcalapp:${{ steps.project.outputs.tag }}

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/alcalapp:${{ steps.project.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: 'Deploy MySQL container'
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_GROUP }} \
            --name mysql-container \
            --image elisaalcala/mydb:latest \
            --environment-variables MYSQL_ROOT_PASSWORD=3301 MYSQL_DATABASE=alcalapp_db \
            --ports 3306
            
      - name: 'Run az commands to deploy container'
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_GROUP }} \
            --name alcalapp \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/alcalapp:latest \
            --dns-name-label elisaalcala-alcalapp \
            --ports 8080
