name: Develop Release

on:
  push:
    branches:
      - develop

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"  # Verifica que el mensaje de commit no contenga [skip ci]
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: elisaalcala/mydb:latest
        env:
          MYSQL_ROOT_PASSWORD: 3301
          MYSQL_DATABASE: alcalapp_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3
    
    env: # Entorno global
      DB_URL: jdbc:mysql://localhost:3306/alcalapp_db?serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 3301
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get Current Version
        id: get_version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Determine Version Increment
        id: determine_increment
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          CURRENT_VERSION=${{ env.CURRENT_VERSION }}
          
          if [[ "$COMMIT_MSG" == *"fix:"* ]]; then
            # Incrementar patch
            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          elif [[ "$COMMIT_MSG" == *"feat:"* ]]; then
            # Incrementar minor y resetear patch
            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$(NF-1)++; $NF=0; print}')
          elif [[ "$COMMIT_MSG" == *"!:"* ]]; then
            # Incrementar major y resetear minor y patch
            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$1++; $(NF-1)=0; $NF=0; print}')
          else
            echo "No se encontró ningún patrón de incremento en el mensaje de commit. No se realizarán cambios."
            exit 0  # Salir sin errores
          fi
          
          echo "NEW_VERSION=${NEW_VERSION}-SNAPSHOT" >> $GITHUB_ENV

      - name: Set New Version
        if: env.NEW_VERSION != ''
        run: |
          mvn versions:set -DnewVersion=${{ env.NEW_VERSION }}

      - name: Commit and push changes to develop
        if: env.NEW_VERSION != ''
        run: |
          git config --global user.name "elisaalcala"
          git config --global user.email "elisaalcgue@gmail.com"
          git add pom.xml
          git commit -m "Update version to ${{ env.NEW_VERSION }} [skip ci]"
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
