name: Master Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed  # Se activa cuando se cierra el PR (mergeado a master)

jobs:
  release:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest
    
    services:
          mysql:
            image: elisaalcala/mydb:latest
            env:
              MYSQL_ROOT_PASSWORD: 3301
              MYSQL_DATABASE: alcalapp_db
            ports:
              - 3306:3306
            options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

    env: # Global environment
      DB_URL: jdbc:mysql://localhost:3306/alcalapp_db?serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 3301
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master  # Asegura que estamos en la rama master

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get Current Version
        id: get_version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Increment Major Version
        run: |
          NEW_VERSION=$(echo ${{ env.CURRENT_VERSION }} | awk -F. -v OFS=. '{$(NF-2)++; $(NF-1)=0; $(NF)=0;print}' | sed 's/-SNAPSHOT//')
          mvn versions:set -DnewVersion=$NEW_VERSION

      - name: Commit and push changes to master
        run: |
          git config --global user.name "elisaalcala"
          git config --global user.email "elisaalcgue@gmail.com"
          git add pom.xml
          git commit -m "Update major version [skip ci]"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update develop branch with new version
        run: |
          git fetch origin
          git checkout develop  # Cambiar a la rama develop
          git merge master  # Mergear cambios de master en la rama develop
          git push origin develop  # Empujar cambios a la rama develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
