name: Publish Docker Image

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: elisaalcala/mydb:latest
        env:
          MYSQL_ROOT_PASSWORD: 3301
          MYSQL_DATABASE: alcalapp_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

    env: # Global environment variables
      DB_URL: jdbc:mysql://localhost:3306/alcalapp_db?serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 3301
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: mvn test
        
      - name: Generate tag
        run: echo "tag=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)" >> $GITHUB_OUTPUT
        id: project
        
      - name: Generate Docker image
        run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/prueba:${{ steps.project.outputs.tag }}

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/prueba:${{ steps.project.outputs.tag }}
