name: Maven Release

on:
  push:
    branches:
      - master
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure Git
        run: |
          git config --global user.email "elisaalcgue@gmail.com"
          git config --global user.name "elisaalcala"
    
      - name: Build and Release
        env:
          MAVEN_OPTS: "-Xmx1024m"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean release:prepare release:perform -B

