name: Maven CI/CD

on:
  push:
    branches:
      - main  # Ejecuta este workflow cuando haya un push a la rama principal
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 3301
          MYSQL_DATABASE: alcalapp_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Cambiamos a JDK 17
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Run Spring Boot application
      run: mvn spring-boot:run &
      env:
        DB_URL: jdbc:mysql://localhost:3306/alcalapp_db?serverTimezone=UTC
        DB_USERNAME: root
        DB_PASSWORD: 3301
