name: Continuous integration example

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      temp-mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 3301
          MYSQL_DATABASE: alcalapp_db
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Wait for MySQL to be ready
        run: |
          until docker exec ${{ job.services.temp-mysql.id }} mysqladmin ping --silent; do
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Run tests
        env:
          DB_URL: jdbc:mysql://localhost:3306/alcalapp_db?serverTimezone=UTC
          DB_USERNAME: root
          DB_PASSWORD: 3301
        run: mvn test
